name: Check Markdown links

on:
  repository_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: 'website/mlc_config.json'
        folder-path: 'docs'
